name: Homebrew bump packages
on:
  workflow_dispatch:
  schedule:
  - cron: "30 2 * * *"

jobs:
  autobump:
    runs-on: macos-26
    steps:
    - name: Bump packages
      uses: Homebrew/actions/bump-packages@main
      with:
        # Custom GitHub access token with only the 'public_repo' scope enabled
        token: ${{secrets.AUTOBUMP_TOKEN}}
        # Bump only these formulae if outdated
        # formulae: >
        #   FORMULA-1
        #   FORMULA-2
        #   FORMULA-3
        #   ...
        # Bump only these casks if outdated
        # casks: >
        #   CASK-1
        #   CASK-2
        #   CASKS-3
        #   ...
        # Do not use a fork for opening PR's
        fork: false
