name: Homebrew bump packages
on:
  workflow_dispatch:
  schedule:
  - cron: "30 2 * * *"

jobs:
  autobump:
    runs-on: macos-26
    steps:
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up git
      uses: Homebrew/actions/git-user-config@main
      with:
        username: slickag

    - name: Bump packages
      id: autobump
      run: brew bump --open-pr --full-name --tap "${GITHUB_REPOSITORY}"
      shell: bash
      env:
        HOMEBREW_DEVELOPER: "1"
        HOMEBREW_GITHUB_API_TOKEN: ${{secrets.AUTOBUMP_TOKEN}}
