name: brew test-bot

on:
  push:
    branches:
      - main
    paths:
      - '**.rb'
  pull_request:
    paths:
      - '**.rb'

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_ANALYTICS: 1

defaults:
  run:
    shell: bash -xeuo pipefail {0}

concurrency:
  group: cache-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test-bot:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-26, macos-15, macos-15-intel, macos-14 ]
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      checks: read
      contents: read
      packages: read
      pull-requests: read
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get cache key
        id: cache-key
        run: |
          cache_key_prefix="${RUNNER_OS}"
          if [ "${RUNNER_OS}" = macOS ]
          then
            macos_version="$(sw_vers -productVersion)"
            cache_key_prefix="macos${macos_version%%.*}-$(uname -m)"
          elif [ "${RUNNER_OS}" = Linux ]
          then
            cache_key_prefix="linux-$(uname -m)"
          fi
          echo "prefix=${cache_key_prefix}" >> "${GITHUB_OUTPUT}"

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ steps.cache-key.outputs.prefix }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ steps.cache-key.outputs.prefix }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Cleanup runner
        run: brew test-bot --only-cleanup-before        

      - name: Setup Homebrew test environment
        run: brew test-bot --only-setup

      - name: Formulae detect
        id: formulae-detect
        run: brew test-bot --only-formulae-detect

      - name: Install FUSE-T
        if: matrix.os != 'ubuntu-latest'
        run: |
          brew install --cask fuse-t
          /bin/bash -c /Users/runner/work/homebrew-knickknacks/homebrew-knickknacks/cmd/fuse-t-links-add > /dev/null

      - run: brew test-bot --only-tap-syntax
      - name: Base64-encode GITHUB_TOKEN for HOMEBREW_DOCKER_REGISTRY_TOKEN
        id: base64-encode
        if: github.event_name == 'pull_request'
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          base64_token=$(echo -n "${TOKEN}" | base64 | tr -d "\n")
          echo "::add-mask::${base64_token}"
          echo "token=${base64_token}" >> "${GITHUB_OUTPUT}"
      - run: brew test-bot --only-formulae --root-url=https://ghcr.io/v2/slickag/knickknacks
        name: Build bottle
        if: github.event_name == 'pull_request' && matrix.os != 'macos-15-intel'
        env:
          HOMEBREW_DOCKER_REGISTRY_TOKEN: ${{ steps.base64-encode.outputs.token }}
      # - run: brew test-bot --only-formulae --only-json-tab --skip-online-checks --skip-recursive-dependents --build-dependents-from-source --root-url=https://ghcr.io/v2/slickag/knickknacks
      - run: |
          cp /Users/runner/work/homebrew-knickknacks/homebrew-knickknacks/cmd/tb_formulae.rb "$(brew --prefix)/Library/Homebrew/test_bot/formulae.rb"
          brew test-bot --only-formulae --root-url=https://ghcr.io/v2/slickag/knickknacks
        if: github.event_name == 'pull_request' && matrix.os == 'macos-15-intel'
        name: Build bottle (Intel)
        id: build-bottle-intel
        env:
          HOMEBREW_DOCKER_REGISTRY_TOKEN: ${{ steps.base64-encode.outputs.token }}
          HOMEBREW_NO_INSTALL_FROM_API: 1
          TESTING_FORMULAE: ${{ steps.formulae-detect.outputs.testing_formulae }}

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: bottles_${{ steps.cache-key.outputs.prefix }}
          path: '*.bottle.*'
